version: '3.4'

services:
  financeoperation.api:
    image: ${DOCKER_REGISTRY-}fonapi
    build:
      context: .
      dockerfile: FinanceOperation.Api/Dockerfile

  financeoperation.blazorwebassembly:
    image: ${DOCKER_REGISTRY-}fonblazorwebass
    build:
      context: .
      dockerfile: FinanceOperation.BlazorWebAssembly/Dockerfile
