// <auto-generated />
using System;
using FinanceOperation.Api.Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceOperation.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230728164157_UpdatePropositionsEntity")]
    partial class UpdatePropositionsEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceOperation.Api.Domain.Propositions.DepositProposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("PropositionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Summary")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Deposits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDateTime = new DateTime(2023, 7, 28, 16, 41, 56, 907, DateTimeKind.Utc).AddTicks(3238),
                            IsDeleted = false,
                            Percentage = 1000.0,
                            PropositionNumber = "148fa3d9-5bc4-4f0d-a0f1-634f745f7639",
                            StartDateTime = new DateTime(2023, 7, 28, 16, 41, 56, 907, DateTimeKind.Utc).AddTicks(3237),
                            Summary = 1000.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Percentage = 102.0,
                            PropositionNumber = "422f13f1-ea71-40cf-8f9c-6ec711e187a3",
                            StartDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = 10001.0
                        });
                });

            modelBuilder.Entity("FinanceOperation.Api.Domain.Users.UserIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kon@gmail.com",
                            FirstName = "Maksym",
                            Password = "password",
                            SecondName = "Konotop"
                        });
                });

            modelBuilder.Entity("FinanceOperation.Domain.Propositions.CreditProposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("PropositionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Summary")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Credits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Percentage = 1000.0,
                            PropositionNumber = "048dce4a-6fda-4c7b-a7d3-2e838c62b62a",
                            StartDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            EndDateTime = new DateTime(2023, 7, 28, 16, 41, 56, 907, DateTimeKind.Utc).AddTicks(3125),
                            IsDeleted = false,
                            Percentage = 102.0,
                            PropositionNumber = "1effffb5-209f-4523-be11-de814cb23e9e",
                            StartDateTime = new DateTime(2023, 7, 28, 16, 41, 56, 907, DateTimeKind.Utc).AddTicks(3125),
                            Summary = 10001.0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FinanceOperation.Api.Domain.Propositions.DepositProposition", b =>
                {
                    b.HasOne("FinanceOperation.Api.Domain.Users.UserIdentity", null)
                        .WithMany("Deposits")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FinanceOperation.Domain.Propositions.CreditProposition", b =>
                {
                    b.HasOne("FinanceOperation.Api.Domain.Users.UserIdentity", null)
                        .WithMany("Credits")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FinanceOperation.Api.Domain.Users.UserIdentity", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("Deposits");
                });
#pragma warning restore 612, 618
        }
    }
}
